function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function valid(board,i,n){const x=i%9,y=Math.floor(i/9);for(let k=0;k<9;k++){if(board[y*9+k]===n||board[k*9+x]===n||board[(Math.floor(y/3)*3+Math.floor(k/3))*9+Math.floor(x/3)*3+k%3]===n)return false;}return true;}
function solutions(board,limit=2){const i=board.indexOf(0);if(i<0)return 1;let count=0;for(let n=1;n<=9;n++)if(valid(board,i,n)){board[i]=n;count+=solutions(board,limit-count);board[i]=0;if(count>=limit)break;}return count;}
function fresh(difficulty=state?.difficulty||'medium'){const digits=shuffle([1,2,3,4,5,6,7,8,9]),groups=()=>shuffle([0,1,2]).flatMap(g=>shuffle([0,1,2]).map(n=>g*3+n)),rows=groups(),cols=groups();const solution=rows.flatMap(r=>cols.map(c=>digits[(r*3+Math.floor(r/3)+c)%9])),givens=solution.slice();let removed=0;for(const i of shuffle(Array.from({length:81},(_,i)=>i))){const value=givens[i];givens[i]=0;if(solutions(givens.slice())!==1)givens[i]=value;else removed++;if(removed>=({easy:34,medium:42,hard:50}[difficulty]))break;}return {difficulty,givens,solution,board:givens.slice(),hints:0};}
load(null);if(!state){state=fresh();save();}
state.difficulty??='medium';
shell(`<div class="sudoku-heading"><div><p class="eyebrow">A MOMENT OF FOCUS</p><h2>One number at a time.</h2></div><label class="difficulty-choice">Difficulty<select id="difficulty"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><button id="new">New puzzle <span aria-hidden="true">↗</span></button></div>
<div class="sudoku-workspace"><section class="puzzle-frame" aria-label="Sudoku puzzle"><div class="puzzle-caption"><span>Classic · 9 × 9</span><span id="score"></span></div><div id="board" class="sudoku-board" role="grid" aria-label="Sudoku board" aria-rowcount="9" aria-colcount="9"></div><div class="puzzle-footer"><span id="completed"></span><span>Unique solution</span></div></section>
<aside class="sudoku-side"><section class="panel"><div class="keypad-heading"><h2>Your next move</h2><span>01 — 09</span></div><p class="keypad-help">Select a square, then a number.</p><div id="keypad" class="number-pad"></div><button id="erase" class="erase">⌫ <span>Erase entry</span></button><div class="assist-actions"><button id="check">Check</button><button id="hint">Hint <span id="hints"></span></button></div></section><div class="sudoku-guide"><span class="guide-mark">✦</span><p>Each row, column and 3 × 3 box contains the numbers 1 through 9.</p><p class="keyboard-hint">↑ ↓ ← → to move<br>1–9 to enter · Delete to erase</p></div></aside></div>`);
$('#difficulty').value=state.difficulty;
let selected=state.givens.indexOf(0),showErrors=false;
function peers(i,j){return Math.floor(i/9)===Math.floor(j/9)||i%9===j%9||(Math.floor(i/27)===Math.floor(j/27)&&Math.floor(i%9/3)===Math.floor(j%9/3));}
function render(){
  const number=state.board[selected];
  $('#board').innerHTML=Array.from({length:9},(_,row)=>`<div class="sudoku-row" role="row">${Array.from({length:9},(_,col)=>{const i=row*9+col,v=state.board[i];const classes=['sudoku-cell',state.givens[i]?'given':'entry',i===selected?'is-selected':peers(i,selected)?'is-peer':'',number&&v===number?'same-number':'',showErrors&&v&&v!==state.solution[i]?'is-error':''].filter(Boolean).join(' ');return `<button class="${classes}" role="gridcell" data-cell="${i}" aria-rowindex="${row+1}" aria-colindex="${col+1}" aria-selected="${i===selected}" aria-readonly="${!!state.givens[i]}" aria-label="Row ${row+1}, column ${col+1}, ${v||'empty'}${state.givens[i]?', given':''}" tabindex="${i===selected?0:-1}"><span>${v||''}</span></button>`;}).join('')}</div>`).join('');
  $('#keypad').innerHTML=Array.from({length:9},(_,i)=>{const n=i+1,remaining=Math.max(0,9-state.board.filter(v=>v===n).length);return `<button data-number="${n}" aria-label="Enter ${n}" class="${n===number?'active':''}"><span>${n}</span><small>${remaining} left</small></button>`;}).join('');
  const filled=state.board.filter(Boolean).length;$('#score').textContent=filled+' / 81';$('#completed').textContent=Math.round(filled/81*100)+'% filled';$('#hints').textContent=state.hints?'· '+state.hints:'';$('#erase').disabled=!!state.givens[selected]||!state.board[selected];
  if(state.board.every((v,i)=>v===state.solution[i])){message('Beautifully done. Puzzle solved.');$('#board').classList.add('solved');}
}
function choose(i,focus=false){selected=i;render();if(focus)document.querySelector(`[data-cell="${i}"]`).focus({preventScroll:true});}
function enter(value){if(state.givens[selected]){message('This is a given number. Choose an empty square.');return;}if(state.board[selected]===value)return;state.board[selected]=value;save();message('');render();}
$('#board').onclick=e=>{const cell=e.target.closest('[data-cell]');if(cell)choose(Number(cell.dataset.cell),true);};
$('#keypad').onclick=e=>{const button=e.target.closest('[data-number]');if(button)enter(Number(button.dataset.number));};
$('#erase').onclick=()=>enter(0);
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.tagName==='SELECT')return;const offset={ArrowLeft:-1,ArrowRight:1,ArrowUp:-9,ArrowDown:9}[e.key];if(offset){e.preventDefault();const next=selected+offset;if(next>=0&&next<81)choose(next,true);}else if(/^[1-9]$/.test(e.key)){e.preventDefault();enter(Number(e.key));}else if(['Backspace','Delete','0'].includes(e.key)){e.preventDefault();enter(0);}});
$('#check').onclick=()=>{showErrors=true;const wrong=state.board.filter((v,i)=>v&&v!==state.solution[i]).length;message(wrong?wrong+' entries highlighted. Take another look.':'All entered numbers are correct.');render();};
$('#hint').onclick=()=>{if(state.givens[selected]){message('Select an editable square first.');return;}if(state.board[selected]===state.solution[selected])return;state.hints++;enter(state.solution[selected]);};
$('#new').onclick=()=>{if(confirm('Start a new puzzle? Your current board will be replaced.')){state=fresh($('#difficulty').value);selected=state.givens.indexOf(0);showErrors=false;save();message('');render();}else $('#difficulty').value=state.difficulty;};
$('#difficulty').onchange=()=>$('#new').click();
render();
