import {Chess} from './vendor/chess.js';
load({pgn:''});const game=new Chess();if(state.pgn)game.loadPgn(state.pgn);
shell('<div class="toolbar"><button id="new">New game</button><button id="undo">Undo move</button><strong id="turn"></strong></div><section id="outcome" class="chess-outcome" role="status" aria-live="polite" hidden><h2 id="outcome-title"></h2><p id="outcome-detail"></p></section><div class="chess-layout"><section><div id="opponent" class="player-label"></div><div id="chess-board" role="grid" aria-label="Chess board"></div><div id="player" class="player-label"></div></section><aside class="panel"><h2>Two players. One board.</h2><p>The side to move is always at the bottom. The board flips after each legal move.</p><div id="promotion" hidden><p>Promote your pawn</p><div class="toolbar"><button data-promotion="q">Queen</button><button data-promotion="r">Rook</button><button data-promotion="b">Bishop</button><button data-promotion="n">Knight</button></div></div><div id="material"></div><h2>Move history</h2><div id="moves"></div></aside></div>');
const glyph={k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'},names={k:'king',q:'queen',r:'rook',b:'bishop',n:'knight',p:'pawn'};let selected=null,pending=null;
function render(){const turn=game.turn(),black=turn==='b',files=black?'hgfedcba':'abcdefgh',ranks=black?'12345678':'87654321',legal=selected?game.moves({square:selected,verbose:true}):[],last=game.history({verbose:true}).at(-1);$('#chess-board').innerHTML=[...ranks].flatMap((rank,row)=>[...files].map((file,col)=>{const square=file+rank,piece=game.get(square),target=legal.some(m=>m.to===square);return `<button role="gridcell" class="square ${(file.charCodeAt(0)+Number(rank))%2?'light-square':'dark-square'} ${selected===square?'selected-square':''} ${piece?.type==='k'&&piece.color===turn&&game.isCheck()?'king-in-check':''} ${last&&(last.from===square||last.to===square)?'last-move':''}" data-square="${square}" aria-label="${square}${piece?' '+(piece.color==='w'?'white ':'black ')+names[piece.type]:', empty'}${target?', legal destination':''}">${piece?`<span class="piece ${piece.color==='w'?'white-piece':'black-piece'}">${glyph[piece.type]}</span>`:''}${target?'<i class="legal-dot"></i>':''}${col===0?'<small class="rank-label">'+rank+'</small>':''}${row===7?'<small class="file-label">'+file+'</small>':''}</button>`;})).join('');$('#player').textContent=(black?'Black':'White')+' · to move';$('#opponent').textContent=black?'White':'Black';$('#undo').disabled=!game.history().length;$('#turn').textContent=game.isCheckmate()?(black?'White':'Black')+' wins by checkmate':game.isStalemate()?'Draw · stalemate':game.isThreefoldRepetition()?'Draw · repetition':game.isInsufficientMaterial()?'Draw · insufficient material':game.isDraw()?'Draw':(black?'Black':'White')+' to move'+(game.isCheck()?' · check':'');renderMaterial();const history=game.history();$('#moves').innerHTML=Array.from({length:Math.ceil(history.length/2)},(_,i)=>`<div class="move-row"><small>${i+1}.</small><span>${esc(history[i*2])}</span><span>${esc(history[i*2+1]||'')}</span></div>`).join('')||'<p>No moves yet.</p>';}
function renderMaterial(){
 const values={p:1,n:3,b:3,r:5,q:9,k:0},moves=game.history({verbose:true}),captures={w:[],b:[]};for(const m of moves)if(m.captured)captures[m.color].push(m.captured);
 const totals={w:0,b:0};for(const row of game.board())for(const p of row)if(p)totals[p.color]+=values[p.type];const difference=totals.w-totals.b;
 $('#material').innerHTML=['w','b'].map(color=>{const taken=captures[color].sort((a,b)=>values[b]-values[a]),points=taken.reduce((sum,p)=>sum+values[p],0);return '<div class="capture-row"><div class="capture-heading"><strong>'+ (color==='w'?'White':'Black')+' captures</strong><span>'+points+' pts</span></div><div class="captured-pieces">'+(taken.map(p=>'<span class="piece '+(color==='w'?'black-piece':'white-piece')+'" title="'+names[p]+' · '+values[p]+' points" aria-label="'+names[p]+'">'+glyph[p]+'</span>').join('')||'<small>None yet</small>')+'</div></div>';}).join('')+'<p class="material-lead">'+(difference===0?'Material is equal':(difference>0?'White':'Black')+' leads by '+Math.abs(difference)+' points')+'</p><p class="piece-values">Pawn 1 · Knight 3 · Bishop 3 · Rook 5 · Queen 9</p>';
 const over=game.isGameOver();$('#outcome').hidden=!over;$('#turn').classList.toggle('in-check',game.isCheck()&&!over);
 if(over){$('#outcome-title').textContent=game.isCheckmate()?(game.turn()==='w'?'Black':'White')+' wins — Checkmate':'Game drawn';$('#outcome-detail').textContent=game.isCheckmate()?'The king is in check and no legal escape remains.':game.isStalemate()?'Stalemate: the side to move has no legal moves and is not in check.':game.isThreefoldRepetition()?'The same position has occurred three times.':game.isInsufficientMaterial()?'Neither side has enough material to deliver checkmate.':'Draw under the fifty-move rule.';}
}
function move(from,to,promotion){try{game.move({from,to,promotion});state.pgn=game.pgn();save();selected=null;pending=null;$('#promotion').hidden=true;message('');render();}catch{message('That move is not legal.');}}
$('#chess-board').onclick=e=>{const b=e.target.closest('[data-square]');if(!b||game.isGameOver()||pending)return;const square=b.dataset.square,piece=game.get(square);if(selected){const choices=game.moves({square:selected,verbose:true}).filter(m=>m.to===square);if(choices.length){if(choices.some(m=>m.promotion)){pending={from:selected,to:square};$('#promotion').hidden=false;message('Choose a promotion piece.');return;}move(selected,square);return;}}selected=piece?.color===game.turn()?square:null;render();};
document.querySelectorAll('[data-promotion]').forEach(b=>b.onclick=()=>{if(pending)move(pending.from,pending.to,b.dataset.promotion);});
$('#undo').onclick=()=>{game.undo();state.pgn=game.pgn();selected=null;pending=null;$('#promotion').hidden=true;save();message('');render();};$('#new').onclick=()=>{if(confirm('Start a new chess game?')){game.reset();state.pgn='';selected=null;pending=null;$('#promotion').hidden=true;save();message('');render();}};render();
