const shapes=[[[1,1,1,1]],[[2,0,0],[2,2,2]],[[0,0,3],[3,3,3]],[[4,4],[4,4]],[[0,5,5],[5,5,0]],[[0,6,0],[6,6,6]],[[7,7,0],[0,7,7]]];
const colors=['#0c1422','#51c6ff','#5680ef','#f9a254','#ffdc5d','#65d79a','#b08aff','#f1768f'];
function pick(){return structuredClone(shapes[Math.floor(Math.random()*shapes.length)]);}
function fresh(difficulty=state?.difficulty||'medium'){return {board:Array.from({length:20},()=>Array(10).fill(0)),piece:pick(),next:pick(),x:3,y:0,score:0,lines:0,status:'playing',difficulty};}
load(fresh());
state.difficulty??='medium';
shell('<div class="toolbar"><label>Difficulty <select id="difficulty"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><button id="toggle">Resume</button><button id="new">New game</button><strong id="score"></strong></div><p>← → move · ↑ rotate · ↓ soft drop · Space hard drop · P pause. Games reopen paused.</p><div style="display:flex;justify-content:center;gap:24px"><canvas id="canvas" width="300" height="600" aria-label="Tetris board"></canvas><div><p>Next</p><canvas id="next" width="120" height="120" aria-label="Next piece"></canvas></div></div><div class="controls"><button data-action="left">←</button><button data-action="rotate">Rotate</button><button data-action="right">→</button><button data-action="down">↓</button><button data-action="drop">Drop</button></div>');
$('#difficulty').value=state.difficulty;
$('#difficulty').onchange=()=>{state.difficulty=$('#difficulty').value;save();};
let running=false,last=0;const ctx=$('#canvas').getContext('2d');
function fits(piece,x,y){return piece.every((row,dy)=>row.every((v,dx)=>!v||(x+dx>=0&&x+dx<10&&y+dy>=0&&y+dy<20&&!state.board[y+dy][x+dx])));}
function lock(){state.piece.forEach((row,dy)=>row.forEach((v,dx)=>{if(v)state.board[state.y+dy][state.x+dx]=v;}));const remaining=state.board.filter(row=>row.some(v=>!v)),count=20-remaining.length;state.board=[...Array.from({length:count},()=>Array(10).fill(0)),...remaining];state.score+=[0,100,300,500,800][count]*(1+Math.floor(state.lines/10));state.lines+=count;state.piece=state.next;state.next=pick();state.x=3;state.y=0;if(!fits(state.piece,state.x,state.y)){state.status='lost';running=false;}}
function down(){if(fits(state.piece,state.x,state.y+1))state.y++;else lock();save();draw();}
function action(name){if(!running)return;if(name==='left'||name==='right'){const x=state.x+(name==='left'?-1:1);if(fits(state.piece,x,state.y))state.x=x;}else if(name==='rotate'){const rotated=state.piece[0].map((_,i)=>state.piece.map(row=>row[i]).reverse());for(const offset of [0,-1,1,-2,2])if(fits(rotated,state.x+offset,state.y)){state.piece=rotated;state.x+=offset;break;}}else if(name==='down'){down();return;}else if(name==='drop'){while(fits(state.piece,state.x,state.y+1)){state.y++;state.score+=2;}lock();}save();draw();}
function cells(context,piece,x,y,alpha=1){context.globalAlpha=alpha;piece.forEach((row,dy)=>row.forEach((v,dx)=>{if(v){context.fillStyle=colors[v];context.fillRect((x+dx)*30+1,(y+dy)*30+1,28,28);}}));context.globalAlpha=1;}
function draw(){ctx.fillStyle=colors[0];ctx.fillRect(0,0,300,600);cells(ctx,state.board,0,0);let ghost=state.y;while(fits(state.piece,state.x,ghost+1))ghost++;cells(ctx,state.piece,state.x,ghost,.22);cells(ctx,state.piece,state.x,state.y);const next=$('#next').getContext('2d');next.clearRect(0,0,120,120);cells(next,state.next,0,0);$('#score').textContent='Score '+state.score+' · Lines '+state.lines+' · Level '+(1+Math.floor(state.lines/10));$('#toggle').textContent=running?'Pause':'Resume';$('#toggle').disabled=state.status!=='playing';message(state.status==='lost'?'Game over. Start a new game.':running?'':'Paused · progress saved');}
function toggle(){if(state.status!=='playing')return;running=!running;last=performance.now();save();draw();}
$('#toggle').onclick=toggle;$('#new').onclick=()=>{if(confirm('Start a new game?')){running=false;state=fresh();save();draw();}};
document.onkeydown=e=>{const name={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',ArrowDown:'down',' ':'drop'}[e.key];if(name){e.preventDefault();action(name);}if(e.key.toLowerCase()==='p')toggle();};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
window.addEventListener('blur',()=>{running=false;save();draw();});
function frame(now){if(running&&now-last>Math.max(90,({easy:1100,medium:800,hard:450}[state.difficulty])-Math.floor(state.lines/10)*65)){last=now;down();}requestAnimationFrame(frame);}draw();requestAnimationFrame(frame);
