function fresh(size=9,mines=10){return {size,mines,bombs:[],opened:[],flags:[],status:'ready',moves:0};}
load(fresh());
shell('<div class="toolbar"><select id="difficulty" aria-label="Difficulty"><option value="9">Easy · 9 × 9 · 10 mines</option><option value="16">Medium · 16 × 16 · 40 mines</option><option value="20">Hard · 20 × 20 · 80 mines</option></select><button id="new">New board</button><label><input type="checkbox" id="flag-mode">Flag mode</label><strong id="score"></strong></div><p>Click to reveal. Right-click to flag. Your first revealed square is always safe.</p><div id="board" class="board" role="group" aria-label="Minefield"></div>');
$('#difficulty').value=state.size;
function neighbors(i){const x=i%state.size,y=Math.floor(i/state.size),out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!(dx||dy))continue;if(x+dx>=0&&x+dx<state.size&&y+dy>=0&&y+dy<state.size)out.push((y+dy)*state.size+x+dx);}return out;}
function adjacent(i){return neighbors(i).filter(n=>state.bombs.includes(n)).length;}
function reveal(i){if(['won','lost'].includes(state.status)||state.flags.includes(i)||state.opened.includes(i))return;if(state.status==='ready'){const safe=[i,...neighbors(i)],pool=Array.from({length:state.size**2},(_,n)=>n).filter(n=>!safe.includes(n));for(let n=pool.length-1;n>0;n--){const j=Math.floor(Math.random()*(n+1));[pool[n],pool[j]]=[pool[j],pool[n]];}state.bombs=pool.slice(0,state.mines);state.status='playing';}state.moves++;
  if(state.bombs.includes(i)){state.status='lost';state.opened.push(i);}else{const stack=[i],seen=new Set(state.opened);while(stack.length){const n=stack.pop();if(seen.has(n)||state.flags.includes(n)||state.bombs.includes(n))continue;seen.add(n);if(!adjacent(n))stack.push(...neighbors(n));}state.opened=[...seen];if(state.opened.length===state.size**2-state.mines)state.status='won';}save();render();}
function flag(i){if(['won','lost'].includes(state.status)||state.opened.includes(i))return;state.flags=state.flags.includes(i)?state.flags.filter(n=>n!==i):[...state.flags,i];save();render();}
function render(){$('#board').style.gridTemplateColumns=`repeat(${state.size},1fr)`;$('#board').style.maxWidth='min(700px, calc(100vh - 280px))';$('#board').innerHTML=Array.from({length:state.size**2},(_,i)=>{const open=state.opened.includes(i),bomb=state.bombs.includes(i),value=open?(bomb?'✹':adjacent(i)||''):state.flags.includes(i)?'⚑':state.status==='lost'&&bomb?'✹':'';return `<button class="cell" style="font-size:${state.size>=16?16:22}px;background:${open?'#162337':'#314765'}" data-cell="${i}" aria-label="Row ${Math.floor(i/state.size)+1} column ${i%state.size+1}: ${open?value||'empty':state.flags.includes(i)?'flagged':'covered'}">${value}</button>`;}).join('');$('#score').textContent=(state.mines-state.flags.length)+' mines · '+state.moves+' moves';message(state.status==='won'?'Minefield cleared!':state.status==='lost'?'Mine found. Start a new board to try again.':'');}
$('#board').onclick=e=>{const b=e.target.closest('[data-cell]');if(b)($('#flag-mode').checked?flag:reveal)(Number(b.dataset.cell));};$('#board').oncontextmenu=e=>{const b=e.target.closest('[data-cell]');if(b){e.preventDefault();flag(Number(b.dataset.cell));}};
$('#new').onclick=()=>{const size=Number($('#difficulty').value);resetGame(()=>fresh(size,size===9?10:size===16?40:80));};render();

$('#difficulty').onchange=()=>$('#new').click();
