load({mode:'focus',focus:25,break:5,remaining:1500,deadline:null,sessions:[]});
shell('<section class="panel center"><div class="toolbar"><button id="focus">Focus</button><button id="break">Break</button></div><h2 id="mode"></h2><div class="metric" id="timer"></div><div class="controls"><button id="toggle">Start</button><button id="reset">Reset timer</button></div><form id="settings"><label>Focus minutes <input name="focus" type="number" min="1" max="180" required></label><label>Break minutes <input name="rest" type="number" min="1" max="60" required></label><button>Apply</button></form><p>Running timers continue while the launcher is closed. Reopen to see the result.</p></section><section class="panel"><h2>Completed focus sessions</h2><div id="history"></div></section>');
$('#settings').elements.focus.value=state.focus;$('#settings').elements.rest.value=state.break;
function remaining(){return state.deadline?Math.max(0,Math.ceil((state.deadline-Date.now())/1000)):state.remaining;}
function render(){const seconds=remaining();if(state.deadline&&seconds===0){if(state.mode==='focus')state.sessions.push({ended:state.deadline,minutes:state.focus});state.deadline=null;state.remaining=0;save();message(state.mode==='focus'?'Focus complete. Time for a break.':'Break complete. Ready to focus?');}$('#timer').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');$('#mode').textContent=state.mode==='focus'?'Focus time':'Take a break';$('#toggle').textContent=state.deadline?'Pause':'Start';$('#history').innerHTML=state.sessions.slice().reverse().map(s=>`<div class="row">${new Date(s.ended).toLocaleString()} · ${s.minutes} minutes</div>`).join('')||'<p>Your completed sessions appear here.</p>';}
$('#toggle').onclick=()=>{if(state.deadline){state.remaining=remaining();state.deadline=null;}else{if(state.remaining===0)state.remaining=state[state.mode]*60;state.deadline=Date.now()+state.remaining*1000;}save();render();};
function reset(mode){state.mode=mode;state.deadline=null;state.remaining=state[mode]*60;save();message('');render();}
$('#reset').onclick=()=>{if(confirm('Reset the current timer?'))reset(state.mode);};
for(const mode of ['focus','break'])$('#'+mode).onclick=()=>{if(!state.deadline||confirm('Stop the current timer and switch mode?'))reset(mode);};
$('#settings').onsubmit=e=>{e.preventDefault();if(state.deadline&&!confirm('Apply durations and restart this timer?'))return;state.focus=Number(e.target.elements.focus.value);state.break=Number(e.target.elements.rest.value);reset(state.mode);};
render();setInterval(render,1000);
