load({amount:1,from:'NZD',to:'USD',rates:null,date:null});
shell('<section class="panel"><h2>Currency converter</h2><form id="convert"><input id="amount" type="number" min="0" max="1000000000000" step="any" aria-label="Amount"><select id="from" aria-label="From currency"></select><button id="swap" type="button" aria-label="Swap currencies">⇄</button><select id="to" aria-label="To currency"></select></form><div id="result" class="metric">—</div><p id="rate-date"></p><button id="refresh">Refresh rates</button><p class="muted">Frankfurter reference rates, updated on working days. These are not bank transaction quotes. Last downloaded rates remain available offline.</p></section>');
$('#amount').value=state.amount;
function options(){const codes=state.rates?Object.keys(state.rates).sort():['NZD','USD','EUR','GBP','AUD','CNY'];for(const key of ['from','to']){$('#'+key).innerHTML=codes.map(code=>`<option>${code}</option>`).join('');$('#'+key).value=state[key];}}
function render(){const rate=state.rates&&state.rates[state.to]/state.rates[state.from];$('#result').textContent=Number.isFinite(rate)?(state.amount*rate).toLocaleString(undefined,{maximumFractionDigits:4})+' '+state.to:'No rates downloaded';$('#rate-date').textContent=state.date?'Reference date: '+state.date+' · 1 '+state.from+' = '+rate.toFixed(6)+' '+state.to:'Connect once to download reference rates.';}
for(const id of ['amount','from','to'])$('#'+id).oninput=()=>{if(!$('#amount').validity.valid)return;state.amount=Number($('#amount').value);state.from=$('#from').value;state.to=$('#to').value;save();render();};
$('#convert').onsubmit=e=>e.preventDefault();
$('#swap').onclick=()=>{[state.from,state.to]=[state.to,state.from];save();options();render();};
async function refresh(){$('#refresh').disabled=true;message('Downloading rates…');try{const result=await window.appStore.rates();if(result.data){state.rates={NZD:1,...result.data.rates};state.date=result.data.date;save();options();render();message(result.stale?'Offline · showing last downloaded rates.':'Rates ready · '+new Date(result.fetchedAt).toLocaleString());}else message('Unable to download rates. Try again when connected.');}catch(e){message(e.message);}finally{$('#refresh').disabled=false;}}
$('#refresh').onclick=refresh;options();render();refresh();
