function fresh(){return {snake:[{x:10,y:10},{x:9,y:10},{x:8,y:10}],direction:{x:1,y:0},food:{x:15,y:10},score:0,best:state?.best||0,status:'playing',speed:140};}
load(null);if(!state){state=fresh();save();}
shell('<div class="toolbar"><button id="toggle">Resume</button><button id="new">New game</button><label>Speed <select id="speed"><option value="200">Easy</option><option value="140">Medium</option><option value="90">Hard</option></select></label><strong id="score"></strong></div><p>Arrow keys / WASD to turn. Space pauses. Reopened games always wait for Resume.</p><canvas id="canvas" width="500" height="500" aria-label="Snake board"></canvas><div class="controls"><button data-dir="left">←</button><button data-dir="up">↑</button><button data-dir="down">↓</button><button data-dir="right">→</button></div>');
let running=false,queued=null,last=0;const ctx=$('#canvas').getContext('2d');$('#speed').value=state.speed;
function draw(){ctx.fillStyle='#0a1421';ctx.fillRect(0,0,500,500);ctx.strokeStyle='#ffffff08';for(let i=0;i<=20;i++){ctx.beginPath();ctx.moveTo(i*25,0);ctx.lineTo(i*25,500);ctx.moveTo(0,i*25);ctx.lineTo(500,i*25);ctx.stroke();}state.snake.forEach((s,i)=>{ctx.fillStyle=i?'#3cae6d':'#99f5a8';ctx.fillRect(s.x*25+2,s.y*25+2,21,21);});ctx.fillStyle='#ff786e';ctx.beginPath();ctx.arc(state.food.x*25+12.5,state.food.y*25+12.5,9,0,Math.PI*2);ctx.fill();$('#score').textContent='Score '+state.score+' · Best '+state.best;$('#toggle').textContent=running?'Pause':'Resume';$('#toggle').disabled=state.status!=='playing';message(state.status==='lost'?'Game over. Start a new game.':state.status==='won'?'You filled the board!':running?'': 'Paused · progress saved');}
function step(){if(queued){state.direction=queued;queued=null;}const head={x:state.snake[0].x+state.direction.x,y:state.snake[0].y+state.direction.y},eat=head.x===state.food.x&&head.y===state.food.y;const body=eat?state.snake:state.snake.slice(0,-1);if(head.x<0||head.x>=20||head.y<0||head.y>=20||body.some(s=>s.x===head.x&&s.y===head.y)){state.status='lost';running=false;}else{state.snake.unshift(head);if(eat){state.score+=10;state.best=Math.max(state.best,state.score);const empty=[];for(let y=0;y<20;y++)for(let x=0;x<20;x++)if(!state.snake.some(s=>s.x===x&&s.y===y))empty.push({x,y});if(empty.length)state.food=empty[Math.floor(Math.random()*empty.length)];else{state.status='won';running=false;}}else state.snake.pop();}save();draw();}
const directions={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}};
function turn(name){const d=directions[name];if(!queued&&(d.x!==-state.direction.x||d.y!==-state.direction.y))queued=d;}
function toggle(){if(state.status!=='playing')return;running=!running;last=performance.now();save();draw();}
document.onkeydown=e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;const dir={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'}[e.key];if(dir){e.preventDefault();turn(dir);}if(e.code==='Space'){e.preventDefault();toggle();}};
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>turn(b.dataset.dir));$('#toggle').onclick=toggle;
$('#new').onclick=()=>{if(confirm('Start a new game?')){running=false;queued=null;state=fresh();state.speed=Number($('#speed').value);save();draw();}};
$('#speed').onchange=e=>{state.speed=Number(e.target.value);save();};window.addEventListener('blur',()=>{running=false;save();draw();});
function frame(now){if(running&&now-last>=state.speed){last=now;step();}requestAnimationFrame(frame);}draw();requestAnimationFrame(frame);
