load({tasks:[],sessions:[]});
shell('<section class="panel"><h2>Study plan</h2><form id="add"><input name="name" placeholder="What will you study?" maxlength="200" required aria-label="Task name"><input name="date" type="date" required aria-label="Due date"><input name="time" type="time" aria-label="Start time"><input name="minutes" type="number" min="1" max="1440" value="30" aria-label="Planned minutes"><button>Add task</button></form><div class="toolbar"><label>Show <select id="filter"><option value="all">All tasks</option><option value="today">Today</option><option value="pending">Pending</option><option value="done">Completed</option></select></label></div><div id="list"></div></section><section class="panel"><h2>Study log</h2><form id="log"><input name="subject" placeholder="Subject" required maxlength="100" aria-label="Subject"><input name="minutes" type="number" min="1" max="1440" value="30" required aria-label="Study minutes"><input name="date" type="date" required aria-label="Study date"><button>Log study time</button></form><div id="sessions"></div></section>');
document.querySelectorAll('[type=date]').forEach(el=>el.value=day());
function render(){const filter=$('#filter').value;$('#list').innerHTML=state.tasks.filter(t=>filter==='all'||(filter==='today'&&t.date===day())||(filter==='pending'&&!t.done)||(filter==='done'&&t.done)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(t=>`<div class="row"><input type="checkbox" data-done="${t.id}" ${t.done?'checked':''} aria-label="Complete ${esc(t.name)}"><div class="grow"><strong>${esc(t.name)}</strong><div class="muted">${esc(t.date)} ${esc(t.time)} · ${t.minutes} min</div></div><button data-edit="${t.id}">Edit</button><button data-delete="${t.id}" aria-label="Delete task">×</button></div>`).join('')||'<p>No tasks in this view.</p>';$('#sessions').innerHTML=state.sessions.slice().reverse().map(s=>`<div class="row"><span class="grow">${esc(s.subject)} · ${s.minutes} min <span class="muted">${esc(s.date)}</span></span><button data-session="${s.id}" aria-label="Delete study log">×</button></div>`).join('')||'<p>Log completed study time here to update your dashboard.</p>';}
$('#add').onsubmit=e=>{e.preventDefault();const f=e.target;state.tasks.push({id:crypto.randomUUID(),name:f.elements.name.value.trim(),date:f.elements.date.value,time:f.elements.time.value,minutes:Number(f.elements.minutes.value),done:false});save();f.elements.name.value='';render();};
$('#log').onsubmit=e=>{e.preventDefault();const f=e.target;state.sessions.push({id:crypto.randomUUID(),subject:f.elements.subject.value.trim(),minutes:Number(f.elements.minutes.value),date:f.elements.date.value});save();f.elements.subject.value='';render();};
$('#filter').onchange=render;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=state.tasks.find(t=>t.id===(b.dataset.edit||b.dataset.delete));if(b.dataset.edit&&t){const name=prompt('Task name',t.name);if(name?.trim())t.name=name.trim();else return;}else if(b.dataset.delete){if(!confirm('Delete this task?'))return;state.tasks=state.tasks.filter(t=>t.id!==b.dataset.delete);}else if(b.dataset.session){if(!confirm('Delete this study log?'))return;state.sessions=state.sessions.filter(s=>s.id!==b.dataset.session);}else return;save();render();});
$('#list').onchange=e=>{const t=state.tasks.find(t=>t.id===e.target.dataset.done);if(t){t.done=e.target.checked;save();}};
render();
