const MAZE=['###################','#o.......#.......o#','#.##.##..#..##.##.#','#.................#','#.##.#.#####.#.##.#','#....#...#...#....#','####.###.#.###.####','#....#.......#....#','#.##.#.## ##.#.##.#','#......#   #......#','#.##.#.#####.#.##.#','#....#...#...#....#','#.######.#.######.#','#.................#','#.##.###.#.###.##.#','#o.......#.......o#','###################'];
const W=19,H=17,T=26,LEVELS={easy:{ghosts:2,pace:290,power:9000,lives:3},medium:{ghosts:3,pace:230,power:6000,lives:3},hard:{ghosts:4,pace:175,power:3500,lives:2}};
const dirs={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}};
function food(){return Object.fromEntries(MAZE.flatMap((row,y)=>[...row].flatMap((c,x)=>c==='.'||c==='o'?[[y*W+x,c==='o'?2:1]]:[])));}
function ghosts(level){return Array.from({length:LEVELS[level].ghosts},(_,i)=>({x:8+i%3,y:9,dir:'up',home:8+i%3}));}
function fresh(difficulty=state?.difficulty||'medium'){const s={difficulty,food:food(),player:{x:9,y:13},dir:'left',next:'left',ghosts:ghosts(difficulty),score:0,lives:LEVELS[difficulty].lives,level:1,power:0,status:'playing',best:state?.best||0};delete s.food[13*W+9];return s;}
load(null);if(!state){state=fresh();save();}
shell('<div class="toolbar"><label>Difficulty <select id="difficulty"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><button id="toggle">Resume</button><button id="new">New game</button><strong id="score"></strong></div><p class="center">Arrow keys / WASD to move · Space to pause · Power pellets turn ghosts blue.</p><canvas id="maze" width="494" height="442" aria-label="Pac-Man maze"></canvas><div class="controls"><button data-dir="left">←</button><button data-dir="up">↑</button><button data-dir="down">↓</button><button data-dir="right">→</button></div>');
$('#difficulty').value=state.difficulty;let running=false,last=0,playerTick=0,ghostTick=0;const ctx=$('#maze').getContext('2d');
function open(x,y){return x>=0&&x<W&&y>=0&&y<H&&MAZE[y][x]!=='#';}
function collision(){for(const g of state.ghosts)if(g.x===state.player.x&&g.y===state.player.y){if(state.power>0){state.score+=200;g.x=g.home;g.y=9;g.dir='up';}else{state.lives--;running=false;state.player={x:9,y:13};state.dir=state.next='left';state.ghosts=ghosts(state.difficulty);state.power=0;if(!state.lives)state.status='lost';break;}}state.best=Math.max(state.best,state.score);}
function movePlayer(){const p=state.player,turn=dirs[state.next];if(open(p.x+turn.x,p.y+turn.y))state.dir=state.next;const d=dirs[state.dir];if(open(p.x+d.x,p.y+d.y)){p.x+=d.x;p.y+=d.y;const key=p.y*W+p.x,pellet=state.food[key];if(pellet){state.score+=pellet===2?50:10;if(pellet===2)state.power=LEVELS[state.difficulty].power;delete state.food[key];}}collision();if(!Object.keys(state.food).length){state.level++;state.food=food();state.player={x:9,y:13};delete state.food[13*W+9];state.ghosts=ghosts(state.difficulty);state.power=0;running=false;}save();}
function moveGhosts(){for(const g of state.ghosts){const reverse={left:'right',right:'left',up:'down',down:'up'}[g.dir];let options=Object.entries(dirs).filter(([,d])=>open(g.x+d.x,g.y+d.y));if(options.length>1)options=options.filter(([name])=>name!==reverse);if(!options.length)continue;const chase=Math.random()<(state.difficulty==='easy'?.55:state.difficulty==='medium'?.75:.92);if(chase)options.sort(([,a],[,b])=>{const distance=d=>Math.abs(g.x+d.x-state.player.x)+Math.abs(g.y+d.y-state.player.y);return (distance(a)-distance(b))*(state.power?-1:1);});const [name,d]=chase?options[0]:options[Math.floor(Math.random()*options.length)];g.dir=name;g.x+=d.x;g.y+=d.y;}collision();save();}
function draw(){ctx.fillStyle='#071122';ctx.fillRect(0,0,W*T,H*T);for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(MAZE[y][x]==='#'){ctx.fillStyle='#172b56';ctx.strokeStyle='#507de4';ctx.lineWidth=1.2;ctx.beginPath();ctx.roundRect(x*T+2,y*T+2,T-4,T-4,5);ctx.fill();ctx.stroke();}else if(state.food[y*W+x]){ctx.fillStyle='#ffdfaa';ctx.beginPath();ctx.arc(x*T+T/2,y*T+T/2,state.food[y*W+x]===2?5:2,0,Math.PI*2);ctx.fill();}}const p=state.player,angle={right:0,down:Math.PI/2,left:Math.PI,up:-Math.PI/2}[state.dir],mouth=running?.2+Math.abs(Math.sin(performance.now()/95))*.35:.25;ctx.fillStyle='#ffdb54';ctx.beginPath();ctx.moveTo(p.x*T+T/2,p.y*T+T/2);ctx.arc(p.x*T+T/2,p.y*T+T/2,10,angle+mouth,angle+Math.PI*2-mouth);ctx.closePath();ctx.fill();state.ghosts.forEach((g,i)=>{const x=g.x*T+T/2,y=g.y*T+T/2;ctx.fillStyle=state.power?'#526bed':['#f17d8d','#cf9cec','#6dd2ce','#f4b276'][i];ctx.beginPath();ctx.arc(x,y,10,Math.PI,0);ctx.lineTo(x+10,y+10);for(let k=3;k>=0;k--)ctx.lineTo(x-10+k*5,y+(k%2?6:10));ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(x-6,y-3,4,6);ctx.fillRect(x+2,y-3,4,6);});$('#score').textContent='Score '+state.score+' · Lives '+state.lives+' · Level '+state.level+' · Best '+state.best;$('#toggle').textContent=running?'Pause':'Resume';$('#toggle').disabled=state.status==='lost';message(state.status==='lost'?'Game over. Start a new game.':running?state.power?'Power: '+(state.power/1000).toFixed(1)+'s':'':'Paused · progress saved');}
function toggle(){if(state.status==='lost')return;running=!running;last=performance.now();save();draw();}
function change(){if(confirm('Start a new game with this difficulty?')){state=fresh($('#difficulty').value);running=false;playerTick=ghostTick=0;save();draw();}else $('#difficulty').value=state.difficulty;}
$('#new').onclick=change;$('#difficulty').onchange=change;$('#toggle').onclick=toggle;
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{state.next=b.dataset.dir;save();});document.onkeydown=e=>{if(['SELECT','INPUT'].includes(e.target.tagName))return;const d={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'}[e.key];if(d){e.preventDefault();state.next=d;}else if(e.code==='Space'){e.preventDefault();toggle();}};window.addEventListener('blur',()=>{running=false;save();draw();});
function frame(now){const dt=Math.min(100,now-last);last=now;if(running){state.power=Math.max(0,state.power-dt);playerTick+=dt;ghostTick+=dt;if(playerTick>=130){playerTick%=130;movePlayer();}if(running&&ghostTick>=Math.max(115,LEVELS[state.difficulty].pace-(state.level-1)*12)){ghostTick=0;moveGhosts();}draw();}requestAnimationFrame(frame);}draw();requestAnimationFrame(frame);
