function fresh(difficulty=state?.difficulty||'medium'){const s={board:Array(16).fill(0),score:0,best:state?.best||0,undo:null,difficulty};spawn(s.board,difficulty);spawn(s.board,difficulty);return s;}
function spawn(board,difficulty=state?.difficulty||'medium'){const empty=board.map((v,i)=>v?null:i).filter(i=>i!==null);if(empty.length)board[empty[Math.floor(Math.random()*empty.length)]]=Math.random()<({easy:1,medium:.9,hard:.7}[difficulty])?2:4;}
load(null);if(!state){state=fresh();save();}
state.difficulty??='medium';
shell('<div class="toolbar"><label>Difficulty <select id="difficulty"><option value="easy">Easy · only 2s</option><option value="medium">Medium</option><option value="hard">Hard · more 4s</option></select></label><strong id="score"></strong><button id="new">New game</button><button id="undo">Undo last move</button></div><p>Use arrow keys or WASD. Merge matching tiles to reach 2048.</p><div id="board" class="board" style="grid-template-columns:repeat(4,1fr)" aria-label="2048 board"></div><div class="controls"><button data-dir="left">←</button><button data-dir="up">↑</button><button data-dir="down">↓</button><button data-dir="right">→</button></div>');
$('#difficulty').value=state.difficulty;
$('#difficulty').onchange=()=>{if(confirm('Start a new board with this difficulty?')){state=fresh($('#difficulty').value);save();render();}else $('#difficulty').value=state.difficulty;};
function move(direction){const before=state.board.slice(),previousScore=state.score;for(let line=0;line<4;line++){const ids=Array.from({length:4},(_,i)=>direction==='left'?line*4+i:direction==='right'?line*4+3-i:direction==='up'?i*4+line:(3-i)*4+line);const values=ids.map(i=>state.board[i]).filter(Boolean),merged=[];for(let i=0;i<values.length;i++){if(values[i]===values[i+1]){merged.push(values[i]*2);state.score+=values[i]*2;i++;}else merged.push(values[i]);}ids.forEach((id,i)=>state.board[id]=merged[i]||0);}
  if(before.every((v,i)=>v===state.board[i]))return;state.undo={board:before,score:previousScore};spawn(state.board);state.best=Math.max(state.best,state.score);save();render();}
function render(){$('#score').textContent='Score '+state.score+' · Best '+state.best;$('#undo').disabled=!state.undo;$('#board').innerHTML=state.board.map(v=>`<div class="cell" style="background:${v?'hsl('+Math.max(20,45-Math.log2(v)*2)+' 55% '+Math.max(28,70-Math.log2(v)*3)+'%)':'#ffffff0a'};color:${v<=4?'#222':'white'}">${v||''}</div>`).join('');const possible=state.board.some((v,i)=>!v||(i%4<3&&v===state.board[i+1])||(i<12&&v===state.board[i+4]));message(!possible?'No moves left. Start a new game or undo.':state.board.some(v=>v>=2048)?'2048 reached! Keep playing for a higher score.':'');}
$('#new').onclick=()=>resetGame(fresh);$('#undo').onclick=()=>{if(!state.undo)return;Object.assign(state,state.undo);state.undo=null;save();render();};
const keys={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'};document.onkeydown=e=>{if(e.target.tagName==='SELECT')return;if(keys[e.key]){e.preventDefault();move(keys[e.key]);}};document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>move(b.dataset.dir));render();
